[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.9"
base64 = "0.13"
actix-web = "4"
serde = {version = "1.0.197", features = ["derive"]}
actix-files = "0.6.6"
regex = "1.3"
little_exif = "0.6.2"